#!/usr/bin/perl -w

use strict;
use warnings;

use Test::More tests => 2;
BEGIN { use_ok('GSAPI') };

my $fail = 0;
foreach my $constname (qw(
    DISPLAY_555_MASK DISPLAY_ALPHA_FIRST DISPLAY_ALPHA_LAST
    DISPLAY_ALPHA_MASK DISPLAY_ALPHA_NONE DISPLAY_BIGENDIAN
    DISPLAY_BOTTOMFIRST DISPLAY_COLORS_CMYK DISPLAY_COLORS_GRAY
    DISPLAY_COLORS_MASK DISPLAY_COLORS_NATIVE DISPLAY_COLORS_RGB
    DISPLAY_DEPTH_1 DISPLAY_DEPTH_12 DISPLAY_DEPTH_16 DISPLAY_DEPTH_2
    DISPLAY_DEPTH_4 DISPLAY_DEPTH_8 DISPLAY_DEPTH_MASK DISPLAY_ENDIAN_MASK
    DISPLAY_FIRSTROW_MASK DISPLAY_LITTLEENDIAN DISPLAY_NATIVE_555
    DISPLAY_NATIVE_565 DISPLAY_TOPFIRST DISPLAY_UNUSED_FIRST
    DISPLAY_UNUSED_LAST DISPLAY_VERSION_MAJOR DISPLAY_VERSION_MINOR)) {
  next if (eval "my \$a = GSAPI::$constname(); 1");
  if ($@ =~ /^Your vendor has not defined Errors macro $constname/) {
    diag( "pass: $@" );
  } else {
    diag( "fail: $@" );
    $fail = 1;
  }

}

ok( $fail == 0 , 'Constants' );
